// Class: ReadNN_normalized
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : NN::NN_normalized
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.05/01       [394497]
Creator        : peters
Date           : Wed Jul 29 10:45:48 2015
Host           : Linux DevLinux 3.19.0-22-generic #22-Ubuntu SMP Tue Jun 16 17:15:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/peters/test/kaggle_flavour/flavours-of-physics-start/baseline_c
Training events: 10000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
Layout: "TANH|100,LINEAR" [neural network layout]
ErrorStrategy: "CROSSENTROPY" [error strategy (regression: sum of squares; classification: crossentropy; multiclass: crossentropy/mutual exclusive cross entropy]
WeightInitialization: "XAVIERUNIFORM" [Weight initialization strategy]
TrainingStrategy: "LearningRate=1e-1,Momentum=0.0,Repetitions=1,ConvergenceSteps=300,BatchSize=20,TestRepetitions=15,WeightDecay=0.001,Regularization=NONE,DropConfig=0.0+0.5+0.5+0.5,DropRepetitions=1,Multithreading=True|LearningRate=1e-2,Momentum=0.5,Repetitions=1,ConvergenceSteps=300,BatchSize=30,TestRepetitions=7,WeightDecay=0.001,Regularization=L2,Multithreading=True,DropConfig=0.0+0.1+0.1+0.1,DropRepetitions=1|LearningRate=1e-2,Momentum=0.3,Repetitions=1,ConvergenceSteps=300,BatchSize=40,TestRepetitions=7,WeightDecay=0.0001,Regularization=L2,Multithreading=True|LearningRate=1e-3,Momentum=0.1,Repetitions=1,ConvergenceSteps=200,BatchSize=70,TestRepetitions=7,WeightDecay=0.0001,Regularization=NONE,Multithreading=True" [defines the training strategies]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
SignalWeightsSum: "1.000000e+03" [Sum of weights of signal; Is used to compute the significance on the fly]
BackgroundWeightsSum: "1.000000e+03" [Sum of weights of background; Is used to compute the significance on the fly]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 43
LifeTime                      LifeTime                      LifeTime                      LifeTime                                                        'F'    [0.000291524396744,0.0158023517579]
FlightDistance                FlightDistance                FlightDistance                FlightDistance                                                  'F'    [1.14414250851,299.777893066]
FlightDistanceError           FlightDistanceError           FlightDistanceError           FlightDistanceError                                             'F'    [0.0799640268087,4.49321699142]
pt                            pt                            pt                            pt                                                              'F'    [354.210357666,40976.8125]
IP                            IP                            IP                            IP                                                              'F'    [0.000546279363334,1.06309843063]
dira                          dira                          dira                          dira                                                            'F'    [0.990089535713,1]
DOCAone                       DOCAone                       DOCAone                       DOCAone                                                         'F'    [1.17062909339e-05,0.738568007946]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCAtwo                                                         'F'    [6.90475326337e-06,0.570136606693]
DOCAthree                     DOCAthree                     DOCAthree                     DOCAthree                                                       'F'    [1.89762954506e-06,0.66944950819]
IP_p0p2                       IP_p0p2                       IP_p0p2                       IP_p0p2                                                         'F'    [0.0021598355379,2.96445679665]
IP_p1p2                       IP_p1p2                       IP_p1p2                       IP_p1p2                                                         'F'    [0.00150139816105,2.74239063263]
isolationa                    isolationa                    isolationa                    isolationa                                                      'F'    [0,22]
isolationb                    isolationb                    isolationb                    isolationb                                                      'F'    [0,24]
isolationc                    isolationc                    isolationc                    isolationc                                                      'F'    [0,26]
isolationd                    isolationd                    isolationd                    isolationd                                                      'F'    [0,9]
isolatione                    isolatione                    isolatione                    isolatione                                                      'F'    [0,9]
isolationf                    isolationf                    isolationf                    isolationf                                                      'F'    [0,6]
iso                           iso                           iso                           iso                                                             'F'    [0,20]
CDF1                          CDF1                          CDF1                          CDF1                                                            'F'    [0.0127889104187,1]
CDF2                          CDF2                          CDF2                          CDF2                                                            'F'    [0.00412744330242,1]
CDF3                          CDF3                          CDF3                          CDF3                                                            'F'    [0.0040788478218,1]
ISO_SumBDT                    ISO_SumBDT                    ISO_SumBDT                    ISO_SumBDT                                                      'F'    [-2.5109577179,0.0242125615478]
p0_IsoBDT                     p0_IsoBDT                     p0_IsoBDT                     p0_IsoBDT                                                       'F'    [-0.831375896931,0.0147065138444]
p1_IsoBDT                     p1_IsoBDT                     p1_IsoBDT                     p1_IsoBDT                                                       'F'    [-0.873817741871,0.00475302385166]
p2_IsoBDT                     p2_IsoBDT                     p2_IsoBDT                     p2_IsoBDT                                                       'F'    [-0.858346819878,0.0147065138444]
p0_track_Chi2Dof              p0_track_Chi2Dof              p0_track_Chi2Dof              p0_track_Chi2Dof                                                'F'    [0.291946321726,2.99803113937]
p1_track_Chi2Dof              p1_track_Chi2Dof              p1_track_Chi2Dof              p1_track_Chi2Dof                                                'F'    [0.272274702787,2.99246025085]
p2_track_Chi2Dof              p2_track_Chi2Dof              p2_track_Chi2Dof              p2_track_Chi2Dof                                                'F'    [0.279122114182,2.97016334534]
p0_pt                         p0_pt                         p0_pt                         p0_pt                                                           'F'    [300.434906006,10212.6113281]
p0_p                          p0_p                          p0_p                          p0_p                                                            'F'    [3022.20239258,177759.625]
p0_eta                        p0_eta                        p0_eta                        p0_eta                                                          'F'    [1.76625525951,5.10630989075]
p0_IP                         p0_IP                         p0_IP                         p0_IP                                                           'F'    [0.0514367967844,7.66314172745]
p0_IPSig                      p0_IPSig                      p0_IPSig                      p0_IPSig                                                        'F'    [2.76572775841,188.024307251]
p1_pt                         p1_pt                         p1_pt                         p1_pt                                                           'F'    [318.385925293,24879.4511719]
p1_p                          p1_p                          p1_p                          p1_p                                                            'F'    [3157.26757812,601951.1875]
p1_eta                        p1_eta                        p1_eta                        p1_eta                                                          'F'    [1.74346756935,4.95556974411]
p1_IP                         p1_IP                         p1_IP                         p1_IP                                                           'F'    [0.0389063954353,5.2802696228]
p1_IPSig                      p1_IPSig                      p1_IPSig                      p1_IPSig                                                        'F'    [2.6559484005,190.734436035]
p2_pt                         p2_pt                         p2_pt                         p2_pt                                                           'F'    [300.038360596,21237.453125]
p2_p                          p2_p                          p2_p                          p2_p                                                            'F'    [3028.45068359,391291.5625]
p2_eta                        p2_eta                        p2_eta                        p2_eta                                                          'F'    [1.75236272812,5.00292396545]
p2_IP                         p2_IP                         p2_IP                         p2_IP                                                           'F'    [0.0307645052671,10.8252296448]
p2_IPSig                      p2_IPSig                      p2_IPSig                      p2_IPSig                                                        'F'    [2.89887952805,139.089401245]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadNN_normalized : public IClassifierReader {

 public:

   // constructor
   ReadNN_normalized( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadNN_normalized" ),
        fNvars( 43 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "LifeTime", "FlightDistance", "FlightDistanceError", "pt", "IP", "dira", "DOCAone", "DOCAtwo", "DOCAthree", "IP_p0p2", "IP_p1p2", "isolationa", "isolationb", "isolationc", "isolationd", "isolatione", "isolationf", "iso", "CDF1", "CDF2", "CDF3", "ISO_SumBDT", "p0_IsoBDT", "p1_IsoBDT", "p2_IsoBDT", "p0_track_Chi2Dof", "p1_track_Chi2Dof", "p2_track_Chi2Dof", "p0_pt", "p0_p", "p0_eta", "p0_IP", "p0_IPSig", "p1_pt", "p1_p", "p1_eta", "p1_IP", "p1_IPSig", "p2_pt", "p2_p", "p2_eta", "p2_IP", "p2_IPSig" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1.00002026557922;
      fVmax[0] = 0.347795844078064;
      fVmin[1] = -1.0006206035614;
      fVmax[1] = 0.279082894325256;
      fVmin[2] = -1.00168287754059;
      fVmax[2] = 0.959842443466187;
      fVmin[3] = -1.0019748210907;
      fVmax[3] = 2.64506840705872;
      fVmin[4] = -1.00028169155121;
      fVmax[4] = 0.435126066207886;
      fVmin[5] = -0.955842912197113;
      fVmax[5] = 1;
      fVmin[6] = -1.00002229213715;
      fVmax[6] = 21.5092906951904;
      fVmin[7] = -1.00002300739288;
      fVmax[7] = 0.97570538520813;
      fVmin[8] = -0.999992787837982;
      fVmax[8] = 6.07498741149902;
      fVmin[9] = -1.00093805789948;
      fVmax[9] = 1.43997979164124;
      fVmin[10] = -1.00088560581207;
      fVmax[10] = 0.29246711730957;
      fVmin[11] = -1;
      fVmax[11] = 1.09090924263;
      fVmin[12] = -1;
      fVmax[12] = 1.08333349227905;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 0.777777791023254;
      fVmin[15] = -1;
      fVmax[15] = 0.777777791023254;
      fVmin[16] = -1;
      fVmax[16] = 2;
      fVmin[17] = -1;
      fVmax[17] = 0.800000071525574;
      fVmin[18] = -0.908789038658142;
      fVmax[18] = 1;
      fVmin[19] = -0.943965315818787;
      fVmax[19] = 1;
      fVmin[20] = -1.00215744972229;
      fVmax[20] = 1;
      fVmin[21] = -0.84850537776947;
      fVmax[21] = 0.97185742855072;
      fVmin[22] = -0.968913793563843;
      fVmax[22] = 0.976471781730652;
      fVmin[23] = -0.865751445293427;
      fVmax[23] = 0.980483651161194;
      fVmin[24] = -0.869060516357422;
      fVmax[24] = 0.993685364723206;
      fVmin[25] = -1.0023490190506;
      fVmax[25] = 0.997437834739685;
      fVmin[26] = -0.957602441310883;
      fVmax[26] = 1.00284337997437;
      fVmin[27] = -1.02189409732819;
      fVmax[27] = 1.01402425765991;
      fVmin[28] = -1.00007951259613;
      fVmax[28] = 2.02692794799805;
      fVmin[29] = -0.999986231327057;
      fVmax[29] = 1.42079186439514;
      fVmin[30] = -1.02549290657043;
      fVmax[30] = 1.00099420547485;
      fVmin[31] = -1.00161063671112;
      fVmax[31] = 0.956378698348999;
      fVmin[32] = -0.999796509742737;
      fVmax[32] = 0.525215625762939;
      fVmin[33] = -1.00069463253021;
      fVmax[33] = 2.04285430908203;
      fVmin[34] = -1.0001939535141;
      fVmax[34] = 0.683935165405273;
      fVmin[35] = -1.03722155094147;
      fVmax[35] = 1.07036590576172;
      fVmin[36] = -1.00140452384949;
      fVmax[36] = 0.789493560791016;
      fVmin[37] = -1.00125086307526;
      fVmax[37] = 1.25771307945251;
      fVmin[38] = -0.999998927116394;
      fVmax[38] = 1.49739241600037;
      fVmin[39] = -1.00006365776062;
      fVmax[39] = 1.3622133731842;
      fVmin[40] = -0.977215349674225;
      fVmax[40] = 1.0748302936554;
      fVmin[41] = -0.998199701309204;
      fVmax[41] = 0.951627373695374;
      fVmin[42] = -1.00146532058716;
      fVmax[42] = 0.924396634101868;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';
      fType[39] = 'F';
      fType[40] = 'F';
      fType[41] = 'F';
      fType[42] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadNN_normalized() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][43];
   double fMax_1[3][43];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[43];
   double fVmax[43];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[43];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   inline double ReadNN_normalized::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadNN_normalized::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.000333752832375;
   fMax_1[0][0] = 0.00946494471282;
   fMin_1[1][0] = 0.000291524396744;
   fMax_1[1][0] = 0.0158023517579;
   fMin_1[2][0] = 0.000291524396744;
   fMax_1[2][0] = 0.0158023517579;
   fMin_1[0][1] = 1.16135978699;
   fMax_1[0][1] = 167.990356445;
   fMin_1[1][1] = 1.14414250851;
   fMax_1[1][1] = 299.777893066;
   fMin_1[2][1] = 1.14414250851;
   fMax_1[2][1] = 299.777893066;
   fMin_1[0][2] = 0.0941396653652;
   fMax_1[0][2] = 4.26013803482;
   fMin_1[1][2] = 0.0799640268087;
   fMax_1[1][2] = 4.49321699142;
   fMin_1[2][2] = 0.0799640268087;
   fMax_1[2][2] = 4.49321699142;
   fMin_1[0][3] = 365.319946289;
   fMax_1[0][3] = 29675.1328125;
   fMin_1[1][3] = 354.210357666;
   fMax_1[1][3] = 40976.8125;
   fMin_1[2][3] = 354.210357666;
   fMax_1[2][3] = 40976.8125;
   fMin_1[0][4] = 0.000546279363334;
   fMax_1[0][4] = 1.04605615139;
   fMin_1[1][4] = 0.00113676139154;
   fMax_1[1][4] = 1.06309843063;
   fMin_1[2][4] = 0.000546279363334;
   fMax_1[2][4] = 1.06309843063;
   fMin_1[0][5] = 0.994844257832;
   fMax_1[0][5] = 1;
   fMin_1[1][5] = 0.990089535713;
   fMax_1[1][5] = 1;
   fMin_1[2][5] = 0.990089535713;
   fMax_1[2][5] = 1;
   fMin_1[0][6] = 1.17062909339e-05;
   fMax_1[0][6] = 0.738568007946;
   fMin_1[1][6] = 3.82722901122e-05;
   fMax_1[1][6] = 0.68989610672;
   fMin_1[2][6] = 1.17062909339e-05;
   fMax_1[2][6] = 0.738568007946;
   fMin_1[0][7] = 3.59247969755e-05;
   fMax_1[0][7] = 0.570136606693;
   fMin_1[1][7] = 6.90475326337e-06;
   fMax_1[1][7] = 0.550135791302;
   fMin_1[2][7] = 6.90475326337e-06;
   fMax_1[2][7] = 0.570136606693;
   fMin_1[0][8] = 7.1972654041e-06;
   fMax_1[0][8] = 0.66944950819;
   fMin_1[1][8] = 1.89762954506e-06;
   fMax_1[1][8] = 0.623360812664;
   fMin_1[2][8] = 1.89762954506e-06;
   fMax_1[2][8] = 0.66944950819;
   fMin_1[0][9] = 0.0074284686707;
   fMax_1[0][9] = 2.96445679665;
   fMin_1[1][9] = 0.0021598355379;
   fMax_1[1][9] = 2.85320973396;
   fMin_1[2][9] = 0.0021598355379;
   fMax_1[2][9] = 2.96445679665;
   fMin_1[0][10] = 0.00150139816105;
   fMax_1[0][10] = 1.79367744923;
   fMin_1[1][10] = 0.00227401521988;
   fMax_1[1][10] = 2.74239063263;
   fMin_1[2][10] = 0.00150139816105;
   fMax_1[2][10] = 2.74239063263;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 21;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 22;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 22;
   fMin_1[0][12] = 0;
   fMax_1[0][12] = 22;
   fMin_1[1][12] = 0;
   fMax_1[1][12] = 24;
   fMin_1[2][12] = 0;
   fMax_1[2][12] = 24;
   fMin_1[0][13] = 0;
   fMax_1[0][13] = 24;
   fMin_1[1][13] = 0;
   fMax_1[1][13] = 26;
   fMin_1[2][13] = 0;
   fMax_1[2][13] = 26;
   fMin_1[0][14] = 0;
   fMax_1[0][14] = 4;
   fMin_1[1][14] = 0;
   fMax_1[1][14] = 9;
   fMin_1[2][14] = 0;
   fMax_1[2][14] = 9;
   fMin_1[0][15] = 0;
   fMax_1[0][15] = 8;
   fMin_1[1][15] = 0;
   fMax_1[1][15] = 9;
   fMin_1[2][15] = 0;
   fMax_1[2][15] = 9;
   fMin_1[0][16] = 0;
   fMax_1[0][16] = 4;
   fMin_1[1][16] = 0;
   fMax_1[1][16] = 6;
   fMin_1[2][16] = 0;
   fMax_1[2][16] = 6;
   fMin_1[0][17] = 0;
   fMax_1[0][17] = 13;
   fMin_1[1][17] = 0;
   fMax_1[1][17] = 20;
   fMin_1[2][17] = 0;
   fMax_1[2][17] = 20;
   fMin_1[0][18] = 0.041922044009;
   fMax_1[0][18] = 1;
   fMin_1[1][18] = 0.0127889104187;
   fMax_1[1][18] = 1;
   fMin_1[2][18] = 0.0127889104187;
   fMax_1[2][18] = 1;
   fMin_1[0][19] = 0.00412744330242;
   fMax_1[0][19] = 1;
   fMin_1[1][19] = 0.012580409646;
   fMax_1[1][19] = 1;
   fMin_1[2][19] = 0.00412744330242;
   fMax_1[2][19] = 1;
   fMin_1[0][20] = 0.0040788478218;
   fMax_1[0][20] = 1;
   fMin_1[1][20] = 0.00440155342221;
   fMax_1[1][20] = 1;
   fMin_1[2][20] = 0.0040788478218;
   fMax_1[2][20] = 1;
   fMin_1[0][21] = -2.5109577179;
   fMax_1[0][21] = -0.0160379186273;
   fMin_1[1][21] = -2.12208366394;
   fMax_1[1][21] = 0.0242125615478;
   fMin_1[2][21] = -2.5109577179;
   fMax_1[2][21] = 0.0242125615478;
   fMin_1[0][22] = -0.831375896931;
   fMax_1[0][22] = 0.00671515567228;
   fMin_1[1][22] = -0.762597739697;
   fMax_1[1][22] = 0.0147065138444;
   fMin_1[2][22] = -0.831375896931;
   fMax_1[2][22] = 0.0147065138444;
   fMin_1[0][23] = -0.873817741871;
   fMax_1[0][23] = -0.00323833432049;
   fMin_1[1][23] = -0.766943514347;
   fMax_1[1][23] = 0.00475302385166;
   fMin_1[2][23] = -0.873817741871;
   fMax_1[2][23] = 0.00475302385166;
   fMin_1[0][24] = -0.858346819878;
   fMax_1[0][24] = -0.00956125091761;
   fMin_1[1][24] = -0.758503913879;
   fMax_1[1][24] = 0.0147065138444;
   fMin_1[2][24] = -0.858346819878;
   fMax_1[2][24] = 0.0147065138444;
   fMin_1[0][25] = 0.358640372753;
   fMax_1[0][25] = 2.90568757057;
   fMin_1[1][25] = 0.291946321726;
   fMax_1[1][25] = 2.99803113937;
   fMin_1[2][25] = 0.291946321726;
   fMax_1[2][25] = 2.99803113937;
   fMin_1[0][26] = 0.297275304794;
   fMax_1[0][26] = 2.99246025085;
   fMin_1[1][26] = 0.272274702787;
   fMax_1[1][26] = 2.96419763565;
   fMin_1[2][26] = 0.272274702787;
   fMax_1[2][26] = 2.99246025085;
   fMin_1[0][27] = 0.385306090117;
   fMax_1[0][27] = 2.94574284554;
   fMin_1[1][27] = 0.279122114182;
   fMax_1[1][27] = 2.97016334534;
   fMin_1[2][27] = 0.279122114182;
   fMax_1[2][27] = 2.97016334534;
   fMin_1[0][28] = 300.434906006;
   fMax_1[0][28] = 7689.06982422;
   fMin_1[1][28] = 300.825439453;
   fMax_1[1][28] = 10212.6113281;
   fMin_1[2][28] = 300.434906006;
   fMax_1[2][28] = 10212.6113281;
   fMin_1[0][29] = 3035.35766602;
   fMax_1[0][29] = 144748.09375;
   fMin_1[1][29] = 3022.20239258;
   fMax_1[1][29] = 177759.625;
   fMin_1[2][29] = 3022.20239258;
   fMax_1[2][29] = 177759.625;
   fMin_1[0][30] = 1.77867770195;
   fMax_1[0][30] = 5.00122642517;
   fMin_1[1][30] = 1.76625525951;
   fMax_1[1][30] = 5.10630989075;
   fMin_1[2][30] = 1.76625525951;
   fMax_1[2][30] = 5.10630989075;
   fMin_1[0][31] = 0.0571505390108;
   fMax_1[0][31] = 7.66314172745;
   fMin_1[1][31] = 0.0514367967844;
   fMax_1[1][31] = 5.75640201569;
   fMin_1[2][31] = 0.0514367967844;
   fMax_1[2][31] = 7.66314172745;
   fMin_1[0][32] = 2.9366312027;
   fMax_1[0][32] = 188.024307251;
   fMin_1[1][32] = 2.76572775841;
   fMax_1[1][32] = 170.010314941;
   fMin_1[2][32] = 2.76572775841;
   fMax_1[2][32] = 188.024307251;
   fMin_1[0][33] = 332.139556885;
   fMax_1[0][33] = 20279.1367188;
   fMin_1[1][33] = 318.385925293;
   fMax_1[1][33] = 24879.4511719;
   fMin_1[2][33] = 318.385925293;
   fMax_1[2][33] = 24879.4511719;
   fMin_1[0][34] = 3476.74194336;
   fMax_1[0][34] = 320653.40625;
   fMin_1[1][34] = 3157.26757812;
   fMax_1[1][34] = 601951.1875;
   fMin_1[2][34] = 3157.26757812;
   fMax_1[2][34] = 601951.1875;
   fMin_1[0][35] = 1.74346756935;
   fMax_1[0][35] = 4.89543199539;
   fMin_1[1][35] = 1.78916025162;
   fMax_1[1][35] = 4.95556974411;
   fMin_1[2][35] = 1.74346756935;
   fMax_1[2][35] = 4.95556974411;
   fMin_1[0][36] = 0.0431174300611;
   fMax_1[0][36] = 2.80420064926;
   fMin_1[1][36] = 0.0389063954353;
   fMax_1[1][36] = 5.2802696228;
   fMin_1[2][36] = 0.0389063954353;
   fMax_1[2][36] = 5.2802696228;
   fMin_1[0][37] = 2.6559484005;
   fMax_1[0][37] = 190.734436035;
   fMin_1[1][37] = 2.76773524284;
   fMax_1[1][37] = 153.058364868;
   fMin_1[2][37] = 2.6559484005;
   fMax_1[2][37] = 190.734436035;
   fMin_1[0][38] = 301.25088501;
   fMax_1[0][38] = 18703.953125;
   fMin_1[1][38] = 300.038360596;
   fMax_1[1][38] = 21237.453125;
   fMin_1[2][38] = 300.038360596;
   fMax_1[2][38] = 21237.453125;
   fMin_1[0][39] = 3028.45068359;
   fMax_1[0][39] = 314615.53125;
   fMin_1[1][39] = 3033.20092773;
   fMax_1[1][39] = 391291.5625;
   fMin_1[2][39] = 3028.45068359;
   fMax_1[2][39] = 391291.5625;
   fMin_1[0][40] = 1.78660750389;
   fMax_1[0][40] = 4.92853736877;
   fMin_1[1][40] = 1.75236272812;
   fMax_1[1][40] = 5.00292396545;
   fMin_1[2][40] = 1.75236272812;
   fMax_1[2][40] = 5.00292396545;
   fMin_1[0][41] = 0.0399971678853;
   fMax_1[0][41] = 5.10831451416;
   fMin_1[1][41] = 0.0307645052671;
   fMax_1[1][41] = 10.8252296448;
   fMin_1[2][41] = 0.0307645052671;
   fMax_1[2][41] = 10.8252296448;
   fMin_1[0][42] = 2.99974393845;
   fMax_1[0][42] = 139.089401245;
   fMin_1[1][42] = 2.89887952805;
   fMax_1[1][42] = 133.60369873;
   fMin_1[2][42] = 2.89887952805;
   fMax_1[2][42] = 139.089401245;
}

//_______________________________________________________________________
inline void ReadNN_normalized::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 43;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
      indicesGet.push_back( 17);
      indicesGet.push_back( 18);
      indicesGet.push_back( 19);
      indicesGet.push_back( 20);
      indicesGet.push_back( 21);
      indicesGet.push_back( 22);
      indicesGet.push_back( 23);
      indicesGet.push_back( 24);
      indicesGet.push_back( 25);
      indicesGet.push_back( 26);
      indicesGet.push_back( 27);
      indicesGet.push_back( 28);
      indicesGet.push_back( 29);
      indicesGet.push_back( 30);
      indicesGet.push_back( 31);
      indicesGet.push_back( 32);
      indicesGet.push_back( 33);
      indicesGet.push_back( 34);
      indicesGet.push_back( 35);
      indicesGet.push_back( 36);
      indicesGet.push_back( 37);
      indicesGet.push_back( 38);
      indicesGet.push_back( 39);
      indicesGet.push_back( 40);
      indicesGet.push_back( 41);
      indicesGet.push_back( 42);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
      indicesPut.push_back( 17);
      indicesPut.push_back( 18);
      indicesPut.push_back( 19);
      indicesPut.push_back( 20);
      indicesPut.push_back( 21);
      indicesPut.push_back( 22);
      indicesPut.push_back( 23);
      indicesPut.push_back( 24);
      indicesPut.push_back( 25);
      indicesPut.push_back( 26);
      indicesPut.push_back( 27);
      indicesPut.push_back( 28);
      indicesPut.push_back( 29);
      indicesPut.push_back( 30);
      indicesPut.push_back( 31);
      indicesPut.push_back( 32);
      indicesPut.push_back( 33);
      indicesPut.push_back( 34);
      indicesPut.push_back( 35);
      indicesPut.push_back( 36);
      indicesPut.push_back( 37);
      indicesPut.push_back( 38);
      indicesPut.push_back( 39);
      indicesPut.push_back( 40);
      indicesPut.push_back( 41);
      indicesPut.push_back( 42);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<43;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadNN_normalized::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadNN_normalized::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
