// Class: ReadGBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::GBDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.05/01       [394497]
Creator        : peters
Date           : Thu Jul 30 06:12:14 2015
Host           : Linux DevLinux 3.19.0-22-generic #22-Ubuntu SMP Tue Jun 16 17:15:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/peters/test/kaggle_flavour/flavours-of-physics-start/baseline_c
Training events: 10000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NTrees: "40" [Number of trees in the forest]
MaxDepth: "7" [Max depth of the decision tree allowed]
MinNodeSize: "10" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-02" [Learning rate for GradBoost algorithm]
UseNvars: "6" [Size of the subset of variables used with RandomisedTree option]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 43
LifeTime                      LifeTime                      LifeTime                      LifeTime                                                        'F'    [0.000291524396744,0.0158023517579]
FlightDistance                FlightDistance                FlightDistance                FlightDistance                                                  'F'    [1.14414250851,299.777893066]
FlightDistanceError           FlightDistanceError           FlightDistanceError           FlightDistanceError                                             'F'    [0.0799640268087,4.49321699142]
pt                            pt                            pt                            pt                                                              'F'    [354.210357666,40976.8125]
IP                            IP                            IP                            IP                                                              'F'    [0.000546279363334,1.06309843063]
dira                          dira                          dira                          dira                                                            'F'    [0.990089535713,1]
DOCAone                       DOCAone                       DOCAone                       DOCAone                                                         'F'    [1.17062909339e-05,0.738568007946]
DOCAtwo                       DOCAtwo                       DOCAtwo                       DOCAtwo                                                         'F'    [6.90475326337e-06,0.570136606693]
DOCAthree                     DOCAthree                     DOCAthree                     DOCAthree                                                       'F'    [1.89762954506e-06,0.66944950819]
IP_p0p2                       IP_p0p2                       IP_p0p2                       IP_p0p2                                                         'F'    [0.0021598355379,2.96445679665]
IP_p1p2                       IP_p1p2                       IP_p1p2                       IP_p1p2                                                         'F'    [0.00150139816105,2.74239063263]
isolationa                    isolationa                    isolationa                    isolationa                                                      'F'    [0,22]
isolationb                    isolationb                    isolationb                    isolationb                                                      'F'    [0,24]
isolationc                    isolationc                    isolationc                    isolationc                                                      'F'    [0,26]
isolationd                    isolationd                    isolationd                    isolationd                                                      'F'    [0,9]
isolatione                    isolatione                    isolatione                    isolatione                                                      'F'    [0,9]
isolationf                    isolationf                    isolationf                    isolationf                                                      'F'    [0,6]
iso                           iso                           iso                           iso                                                             'F'    [0,20]
CDF1                          CDF1                          CDF1                          CDF1                                                            'F'    [0.0127889104187,1]
CDF2                          CDF2                          CDF2                          CDF2                                                            'F'    [0.00412744330242,1]
CDF3                          CDF3                          CDF3                          CDF3                                                            'F'    [0.0040788478218,1]
ISO_SumBDT                    ISO_SumBDT                    ISO_SumBDT                    ISO_SumBDT                                                      'F'    [-2.5109577179,0.0242125615478]
p0_IsoBDT                     p0_IsoBDT                     p0_IsoBDT                     p0_IsoBDT                                                       'F'    [-0.831375896931,0.0147065138444]
p1_IsoBDT                     p1_IsoBDT                     p1_IsoBDT                     p1_IsoBDT                                                       'F'    [-0.873817741871,0.00475302385166]
p2_IsoBDT                     p2_IsoBDT                     p2_IsoBDT                     p2_IsoBDT                                                       'F'    [-0.858346819878,0.0147065138444]
p0_track_Chi2Dof              p0_track_Chi2Dof              p0_track_Chi2Dof              p0_track_Chi2Dof                                                'F'    [0.291946321726,2.99803113937]
p1_track_Chi2Dof              p1_track_Chi2Dof              p1_track_Chi2Dof              p1_track_Chi2Dof                                                'F'    [0.272274702787,2.99246025085]
p2_track_Chi2Dof              p2_track_Chi2Dof              p2_track_Chi2Dof              p2_track_Chi2Dof                                                'F'    [0.279122114182,2.97016334534]
p0_pt                         p0_pt                         p0_pt                         p0_pt                                                           'F'    [300.434906006,10212.6113281]
p0_p                          p0_p                          p0_p                          p0_p                                                            'F'    [3022.20239258,177759.625]
p0_eta                        p0_eta                        p0_eta                        p0_eta                                                          'F'    [1.76625525951,5.10630989075]
p0_IP                         p0_IP                         p0_IP                         p0_IP                                                           'F'    [0.0514367967844,7.66314172745]
p0_IPSig                      p0_IPSig                      p0_IPSig                      p0_IPSig                                                        'F'    [2.76572775841,188.024307251]
p1_pt                         p1_pt                         p1_pt                         p1_pt                                                           'F'    [318.385925293,24879.4511719]
p1_p                          p1_p                          p1_p                          p1_p                                                            'F'    [3157.26757812,601951.1875]
p1_eta                        p1_eta                        p1_eta                        p1_eta                                                          'F'    [1.74346756935,4.95556974411]
p1_IP                         p1_IP                         p1_IP                         p1_IP                                                           'F'    [0.0389063954353,5.2802696228]
p1_IPSig                      p1_IPSig                      p1_IPSig                      p1_IPSig                                                        'F'    [2.6559484005,190.734436035]
p2_pt                         p2_pt                         p2_pt                         p2_pt                                                           'F'    [300.038360596,21237.453125]
p2_p                          p2_p                          p2_p                          p2_p                                                            'F'    [3028.45068359,391291.5625]
p2_eta                        p2_eta                        p2_eta                        p2_eta                                                          'F'    [1.75236272812,5.00292396545]
p2_IP                         p2_IP                         p2_IP                         p2_IP                                                           'F'    [0.0307645052671,10.8252296448]
p2_IPSig                      p2_IPSig                      p2_IPSig                      p2_IPSig                                                        'F'    [2.89887952805,139.089401245]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new GBDTNode
   
#ifndef GBDTNode__def
#define GBDTNode__def
   
class GBDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   GBDTNode ( GBDTNode* left,GBDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~GBDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   GBDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   GBDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   GBDTNode*   fLeft;     // pointer to the left daughter node
   GBDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   GBDTNode::~GBDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool GBDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool GBDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadGBDT : public IClassifierReader {

 public:

   // constructor
   ReadGBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadGBDT" ),
        fNvars( 43 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "LifeTime", "FlightDistance", "FlightDistanceError", "pt", "IP", "dira", "DOCAone", "DOCAtwo", "DOCAthree", "IP_p0p2", "IP_p1p2", "isolationa", "isolationb", "isolationc", "isolationd", "isolatione", "isolationf", "iso", "CDF1", "CDF2", "CDF3", "ISO_SumBDT", "p0_IsoBDT", "p1_IsoBDT", "p2_IsoBDT", "p0_track_Chi2Dof", "p1_track_Chi2Dof", "p2_track_Chi2Dof", "p0_pt", "p0_p", "p0_eta", "p0_IP", "p0_IPSig", "p1_pt", "p1_p", "p1_eta", "p1_IP", "p1_IPSig", "p2_pt", "p2_p", "p2_eta", "p2_IP", "p2_IPSig" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;
      fVmin[33] = 0;
      fVmax[33] = 0;
      fVmin[34] = 0;
      fVmax[34] = 0;
      fVmin[35] = 0;
      fVmax[35] = 0;
      fVmin[36] = 0;
      fVmax[36] = 0;
      fVmin[37] = 0;
      fVmax[37] = 0;
      fVmin[38] = 0;
      fVmax[38] = 0;
      fVmin[39] = 0;
      fVmax[39] = 0;
      fVmin[40] = 0;
      fVmax[40] = 0;
      fVmin[41] = 0;
      fVmax[41] = 0;
      fVmin[42] = 0;
      fVmax[42] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';
      fType[39] = 'F';
      fType[40] = 'F';
      fType[41] = 'F';
      fType[42] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadGBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[43];
   double fVmax[43];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[43];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<GBDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadGBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      GBDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(GBDTNode*)current->GetRight();
         else current=(GBDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadGBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.86034,0.0072068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.931704,0.00863408) , 
9, 0.156495, 1, 0, 0.902322,0.402322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00334373) , 
21, -0.758787, 1, 0, 0.826827,0.326827) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00574468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00859625) , 
4, 0.112209, 1, 0, 0.137001,-0.362999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000664506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.0053218) , 
17, 0.809524, 1, 0, 0.402002,-0.0979976) , 
0, 0.00103014, 1, 0, 0.282478,-0.217522) , 
4, 0.051144, 1, 0, 0.5,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.86034,0.00713511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.931704,0.00854838) , 
9, 0.156495, 1, 0, 0.902322,0.398299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00331033) , 
21, -0.758787, 1, 0, 0.826827,0.323559) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00568742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00851092) , 
4, 0.112209, 1, 0, 0.137001,-0.359369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000657861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00526873) , 
17, 0.809524, 1, 0, 0.402002,-0.0970176) , 
0, 0.00103014, 1, 0, 0.282478,-0.215346) , 
4, 0.051144, 1, 0, 0.5,6.15716e-09)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933962,0.00852139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864117,0.007124) , 
25, 1.08637, 1, 0, 0.902322,0.394316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00327733) , 
21, -0.758787, 1, 0, 0.826827,0.320323) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.0056311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00842766) , 
4, 0.112209, 1, 0, 0.137001,-0.355775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000651283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00521648) , 
17, 0.809524, 1, 0, 0.402002,-0.0960475) , 
0, 0.00103014, 1, 0, 0.282478,-0.213193) , 
4, 0.051144, 1, 0, 0.5,8.19862e-09)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.86034,0.00698796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.931704,0.00838873) , 
9, 0.156495, 1, 0, 0.902322,0.390374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00324474) , 
21, -0.758787, 1, 0, 0.826827,0.31712) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00557569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00834639) , 
4, 0.112209, 1, 0, 0.137001,-0.352218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000644772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00516503) , 
17, 0.809524, 1, 0, 0.402002,-0.0950871) , 
0, 0.00103014, 1, 0, 0.282478,-0.211061) , 
4, 0.051144, 1, 0, 0.5,2.39164e-08)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933962,0.00836476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864117,0.00697957) , 
25, 1.08637, 1, 0, 0.902322,0.386471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00321253) , 
21, -0.758787, 1, 0, 0.826827,0.31395) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00552116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00826705) , 
4, 0.112209, 1, 0, 0.137001,-0.348696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000638326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00511436) , 
17, 0.809524, 1, 0, 0.402002,-0.0941363) , 
0, 0.00103014, 1, 0, 0.282478,-0.208951) , 
4, 0.051144, 1, 0, 0.5,3.65585e-08)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.86034,0.0068467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.931704,0.00823638) , 
9, 0.156495, 1, 0, 0.902322,0.382607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00318071) , 
21, -0.758787, 1, 0, 0.826827,0.310811) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00546749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00818955) , 
4, 0.112209, 1, 0, 0.137001,-0.34521) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000631945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00506444) , 
17, 0.809524, 1, 0, 0.402002,-0.0931951) , 
0, 0.00103014, 1, 0, 0.282478,-0.206862) , 
4, 0.051144, 1, 0, 0.5,6.09994e-08)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933962,0.00821523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864117,0.00684086) , 
25, 1.08637, 1, 0, 0.902322,0.378782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00314926) , 
21, -0.758787, 1, 0, 0.826827,0.307704) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00541465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00811382) , 
4, 0.112209, 1, 0, 0.137001,-0.341759) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000625628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00501526) , 
17, 0.809524, 1, 0, 0.402002,-0.0922633) , 
0, 0.00103014, 1, 0, 0.282478,-0.204794) , 
4, 0.051144, 1, 0, 0.5,8.33511e-08)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.86034,0.00671093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.931704,0.00809081) , 
9, 0.156495, 1, 0, 0.902322,0.374996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00311819) , 
21, -0.758787, 1, 0, 0.826827,0.304628) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00536262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.0080398) , 
4, 0.112209, 1, 0, 0.137001,-0.338343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000619375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00496679) , 
17, 0.809524, 1, 0, 0.402002,-0.0913408) , 
0, 0.00103014, 1, 0, 0.282478,-0.202747) , 
4, 0.051144, 1, 0, 0.5,1.11467e-07)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00636959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00797602) , 
9, 0.156495, 1, 0, 0.891855,0.363191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00268254) , 
22, -0.212656, 1, 0, 0.826827,0.301583) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00531138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00796743) , 
4, 0.112209, 1, 0, 0.137001,-0.334961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000613186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00491902) , 
17, 0.809524, 1, 0, 0.402002,-0.0904276) , 
0, 0.00103014, 1, 0, 0.282478,-0.20072) , 
4, 0.051144, 1, 0, 0.5,1.48183e-07)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933962,0.00801003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864117,0.00664315) , 
25, 1.08637, 1, 0, 0.902322,0.367758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00304796) , 
21, -0.758787, 1, 0, 0.826827,0.298568) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00526091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00789665) , 
4, 0.112209, 1, 0, 0.137001,-0.331612) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000607057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00487192) , 
17, 0.809524, 1, 0, 0.402002,-0.0895236) , 
0, 0.00103014, 1, 0, 0.282478,-0.198714) , 
4, 0.051144, 1, 0, 0.5,1.60953e-07)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00624928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00784342) , 
9, 0.156495, 1, 0, 0.891855,0.356173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00261928) , 
22, -0.212656, 1, 0, 0.826827,0.295584) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00521118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.0078274) , 
4, 0.112209, 1, 0, 0.137001,-0.328298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000600991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00482549) , 
17, 0.809524, 1, 0, 0.402002,-0.0886286) , 
0, 0.00103014, 1, 0, 0.282478,-0.196727) , 
4, 0.051144, 1, 0, 0.5,1.99917e-07)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00619213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00777473) , 
9, 0.156495, 1, 0, 0.891855,0.352613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00259363) , 
22, -0.212656, 1, 0, 0.826827,0.292629) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00516218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00775962) , 
4, 0.112209, 1, 0, 0.137001,-0.325017) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000594987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00477971) , 
17, 0.809524, 1, 0, 0.402002,-0.0877426) , 
0, 0.00103014, 1, 0, 0.282478,-0.194761) , 
4, 0.051144, 1, 0, 0.5,2.26277e-07)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933962,0.00782142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864117,0.00645991) , 
25, 1.08637, 1, 0, 0.902322,0.357274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00294147) , 
21, -0.758787, 1, 0, 0.826827,0.289705) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00511388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00769327) , 
4, 0.112209, 1, 0, 0.137001,-0.321768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000589042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00473455) , 
17, 0.809524, 1, 0, 0.402002,-0.0868654) , 
0, 0.00103014, 1, 0, 0.282478,-0.192814) , 
4, 0.051144, 1, 0, 0.5,2.47371e-07)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00607778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00765017) , 
9, 0.156495, 1, 0, 0.891855,0.3458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00253268) , 
22, -0.212656, 1, 0, 0.826827,0.286809) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00506627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.0076283) , 
4, 0.112209, 1, 0, 0.137001,-0.318553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000583157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00469001) , 
17, 0.809524, 1, 0, 0.402002,-0.0859971) , 
0, 0.00103014, 1, 0, 0.282478,-0.190887) , 
4, 0.051144, 1, 0, 0.5,2.9e-07)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933962,0.00769889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864117,0.00634394) , 
25, 1.08637, 1, 0, 0.902322,0.350384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00287565) , 
21, -0.758787, 1, 0, 0.826827,0.283943) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00501933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00756465) , 
4, 0.112209, 1, 0, 0.137001,-0.315369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.00057733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00464606) , 
17, 0.809524, 1, 0, 0.402002,-0.0851374) , 
0, 0.00103014, 1, 0, 0.282478,-0.188979) , 
4, 0.051144, 1, 0, 0.5,3.18712e-07)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00596715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00753046) , 
9, 0.156495, 1, 0, 0.891855,0.339119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00247323) , 
22, -0.212656, 1, 0, 0.826827,0.281105) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00497305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00750228) , 
4, 0.112209, 1, 0, 0.137001,-0.312218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532767,0.000892669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271238,-0.00427382) , 
4, 0.147585, 1, 0, 0.402002,-0.0842864) , 
0, 0.00103014, 1, 0, 0.282478,-0.187091) , 
4, 0.051144, 1, 0, 0.5,3.68544e-07)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933962,0.00758114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864117,0.00623185) , 
25, 1.08637, 1, 0, 0.902322,0.343628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00281145) , 
21, -0.758787, 1, 0, 0.826827,0.278296) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00492739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.00744115) , 
4, 0.112209, 1, 0, 0.137001,-0.309098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000586323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00458446) , 
17, 0.809524, 1, 0, 0.402002,-0.0834437) , 
0, 0.00103014, 1, 0, 0.282478,-0.185221) , 
4, 0.051144, 1, 0, 0.5,4.63036e-07)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00586001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00741529) , 
9, 0.156495, 1, 0, 0.891855,0.33257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00241523) , 
22, -0.212656, 1, 0, 0.826827,0.275515) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189276,-0.00514578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0672414,-0.00761602) , 
25, 1.24629, 1, 0, 0.137001,-0.306009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532767,0.000898291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271238,-0.0042147) , 
4, 0.147585, 1, 0, 0.402002,-0.0826096) , 
0, 0.00103014, 1, 0, 0.282478,-0.18337) , 
4, 0.051144, 1, 0, 0.5,5.20298e-07)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926715,0.00738797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861465,0.00613782) , 
25, 1.08637, 1, 0, 0.896989,0.335529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670702,0.00267962) , 
23, -0.222761, 1, 0, 0.826827,0.272762) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,-0.00482607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701876,-0.0073317) , 
4, 0.112209, 1, 0, 0.137001,-0.302951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000594935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00452415) , 
17, 0.809524, 1, 0, 0.402002,-0.0817837) , 
0, 0.00103014, 1, 0, 0.282478,-0.181538) , 
4, 0.051144, 1, 0, 0.5,6.67062e-07)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933962,0.00741286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864117,0.0060746) , 
25, 1.08637, 1, 0, 0.902322,0.333859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00271321) , 
21, -0.758787, 1, 0, 0.826827,0.270037) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189276,-0.00504693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0672414,-0.00750383) , 
25, 1.24629, 1, 0, 0.137001,-0.299924) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532767,0.000903571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271238,-0.00415681) , 
4, 0.147585, 1, 0, 0.402002,-0.0809662) , 
0, 0.00103014, 1, 0, 0.282478,-0.179724) , 
4, 0.051144, 1, 0, 0.5,6.81099e-07)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00570598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00725607) , 
9, 0.156495, 1, 0, 0.891855,0.323194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00231974) , 
22, -0.212656, 1, 0, 0.826827,0.267339) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626122,0.00295972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262956,-0.00395019) , 
22, -0.230639, 1, 0, 0.441076,-0.0275698) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119462,-0.00642498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394252,-0.00171371) , 
0, 0.00116518, 1, 0, 0.261732,-0.196174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0807175,-0.00753619) , 
25, 1.32284, 1, 0, 0.200556,-0.255594) , 
4, 0.0993826, 1, 0, 0.282478,-0.177927) , 
4, 0.051144, 1, 0, 0.5,8.52528e-07)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926715,0.00722629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861465,0.0059874) , 
25, 1.08637, 1, 0, 0.896989,0.326103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670702,0.00258113) , 
23, -0.222761, 1, 0, 0.826827,0.264668) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619298,0.00273342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.0039295) , 
4, 0.0993838, 1, 0, 0.41102,-0.0657397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229061,-0.00432594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0889774,-0.00713872) , 
25, 1.19228, 1, 0, 0.16061,-0.280828) , 
17, 0.952381, 1, 0, 0.282478,-0.17615) , 
4, 0.051144, 1, 0, 0.5,9.6046e-07)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00560856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00715257) , 
9, 0.156495, 1, 0, 0.891855,0.317069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.0022593) , 
22, -0.212656, 1, 0, 0.826827,0.262023) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189276,-0.0049398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0672414,-0.00736558) , 
25, 1.24629, 1, 0, 0.137001,-0.292753) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615319,0.00251576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352252,-0.00245172) , 
4, 0.147585, 1, 0, 0.487527,0.00524536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208704,-0.0052975) , 
25, 1.32089, 1, 0, 0.402002,-0.0771417) , 
0, 0.00103014, 1, 0, 0.282478,-0.174389) , 
4, 0.051144, 1, 0, 0.5,1.14705e-06)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926715,0.00712399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861465,0.00588842) , 
25, 1.08637, 1, 0, 0.896989,0.319938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670702,0.00251872) , 
23, -0.222761, 1, 0, 0.826827,0.259405) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189276,-0.00489717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0672414,-0.00730796) , 
25, 1.24629, 1, 0, 0.137001,-0.289828) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000647199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00435773) , 
17, 0.809524, 1, 0, 0.402002,-0.0763706) , 
0, 0.00103014, 1, 0, 0.282478,-0.172647) , 
4, 0.051144, 1, 0, 0.5,1.27706e-06)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.0055139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00705262) , 
9, 0.156495, 1, 0, 0.891855,0.311063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00220031) , 
22, -0.212656, 1, 0, 0.826827,0.256814) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626122,0.00296238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262956,-0.00380997) , 
22, -0.230639, 1, 0, 0.441076,-0.0237087) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119462,-0.00626163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394252,-0.00162716) , 
0, 0.00116518, 1, 0, 0.261732,-0.189158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0807175,-0.00733879) , 
25, 1.32284, 1, 0, 0.200556,-0.246964) , 
4, 0.0993826, 1, 0, 0.282478,-0.170922) , 
4, 0.051144, 1, 0, 0.5,1.35154e-06)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926715,0.00702517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861465,0.00579234) , 
25, 1.08637, 1, 0, 0.896989,0.313892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670702,0.00245779) , 
23, -0.222761, 1, 0, 0.826827,0.254248) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619298,0.00273452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.00380274) , 
4, 0.0993838, 1, 0, 0.41102,-0.0616289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229061,-0.00418964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0889774,-0.00694454) , 
25, 1.19228, 1, 0, 0.16061,-0.271214) , 
17, 0.952381, 1, 0, 0.282478,-0.169214) , 
4, 0.051144, 1, 0, 0.5,1.44786e-06)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933962,0.00706223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864117,0.00573459) , 
25, 1.08637, 1, 0, 0.902322,0.312425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00248644) , 
21, -0.758787, 1, 0, 0.826827,0.251708) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0936768,-0.00670957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211,-0.00428211) , 
0, 0.000783855, 1, 0, 0.137001,-0.282921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532767,0.000972255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271238,-0.00390607) , 
4, 0.147585, 1, 0, 0.402002,-0.0727121) , 
0, 0.00103014, 1, 0, 0.282478,-0.167523) , 
4, 0.051144, 1, 0, 0.5,1.63431e-06)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00537459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00691183) , 
9, 0.156495, 1, 0, 0.891855,0.302308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00211261) , 
22, -0.212656, 1, 0, 0.826827,0.249194) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189276,-0.00474611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0672414,-0.00713503) , 
25, 1.24629, 1, 0, 0.137001,-0.280094) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615319,0.00250801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352252,-0.0023131) , 
4, 0.147585, 1, 0, 0.487527,0.00846405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208704,-0.00512249) , 
25, 1.32089, 1, 0, 0.402002,-0.0719853) , 
0, 0.00103014, 1, 0, 0.282478,-0.165849) , 
4, 0.051144, 1, 0, 0.5,1.82443e-06)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926715,0.00688197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861465,0.00565674) , 
25, 1.08637, 1, 0, 0.896989,0.305088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670702,0.00236721) , 
23, -0.222761, 1, 0, 0.826827,0.246704) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626122,0.00295828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262956,-0.00368738) , 
22, -0.230639, 1, 0, 0.441076,-0.0204641) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0581297,-0.00717277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191675,-0.00539443) , 
0, 0.000991855, 1, 0, 0.12027,-0.308725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303048,-0.00301779) , 
32, 10.9026, 1, 0, 0.200556,-0.238434) , 
4, 0.0993826, 1, 0, 0.282478,-0.164192) , 
4, 0.051144, 1, 0, 0.5,1.95655e-06)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00528626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00681986) , 
9, 0.156495, 1, 0, 0.891855,0.296589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00205705) , 
22, -0.212656, 1, 0, 0.826827,0.24424) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619298,0.00273242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.00365981) , 
4, 0.0993838, 1, 0, 0.41102,-0.0570791) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229061,-0.00405884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0889774,-0.00678338) , 
25, 1.19228, 1, 0, 0.16061,-0.262549) , 
17, 0.952381, 1, 0, 0.282478,-0.162552) , 
4, 0.051144, 1, 0, 0.5,2.10557e-06)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926715,0.00679106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861465,0.00556711) , 
25, 1.08637, 1, 0, 0.896989,0.29933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670702,0.00230976) , 
23, -0.222761, 1, 0, 0.826827,0.2418) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0936768,-0.00655258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211,-0.004136) , 
0, 0.000783855, 1, 0, 0.137001,-0.273561) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615319,0.00250399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352252,-0.00221219) , 
4, 0.147585, 1, 0, 0.487527,0.0108422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208704,-0.00500708) , 
25, 1.32089, 1, 0, 0.402002,-0.0683883) , 
0, 0.00103014, 1, 0, 0.282478,-0.160928) , 
4, 0.051144, 1, 0, 0.5,2.31546e-06)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933962,0.00683463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864117,0.00551158) , 
25, 1.08637, 1, 0, 0.902322,0.297932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.00233795) , 
21, -0.758787, 1, 0, 0.826827,0.239385) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619298,0.00272224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277778,-0.00359609) , 
4, 0.0993838, 1, 0, 0.41102,-0.0552217) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229061,-0.00399709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0889774,-0.00669379) , 
25, 1.19228, 1, 0, 0.16061,-0.258014) , 
17, 0.952381, 1, 0, 0.282478,-0.15932) , 
4, 0.051144, 1, 0, 0.5,2.43012e-06)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00515586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00669007) , 
9, 0.156495, 1, 0, 0.891855,0.288253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00197435) , 
22, -0.212656, 1, 0, 0.826827,0.236994) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0936768,-0.00647618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211,-0.00407245) , 
0, 0.000783855, 1, 0, 0.137001,-0.269117) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615319,0.00248886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352252,-0.00215224) , 
4, 0.147585, 1, 0, 0.487527,0.0119323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208704,-0.00492357) , 
25, 1.32089, 1, 0, 0.402002,-0.0662109) , 
0, 0.00103014, 1, 0, 0.282478,-0.157728) , 
4, 0.051144, 1, 0, 0.5,2.64972e-06)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926715,0.00665893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861465,0.00544044) , 
25, 1.08637, 1, 0, 0.896989,0.290945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670702,0.00222425) , 
23, -0.222761, 1, 0, 0.826827,0.234627) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626122,0.0029403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262956,-0.00354144) , 
22, -0.230639, 1, 0, 0.441076,-0.0168863) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.162002,-0.00539229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0730067,-0.00699996) , 
25, 1.19057, 1, 0, 0.12027,-0.297044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303048,-0.00285468) , 
32, 10.9026, 1, 0, 0.200556,-0.22809) , 
4, 0.0993826, 1, 0, 0.282478,-0.156153) , 
4, 0.051144, 1, 0, 0.5,2.78961e-06)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00507305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00660502) , 
9, 0.156495, 1, 0, 0.891855,0.282806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00192195) , 
22, -0.212656, 1, 0, 0.826827,0.232283) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0936768,-0.00640053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211,-0.0040104) , 
0, 0.000783855, 1, 0, 0.137001,-0.264695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.00077956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00400363) , 
17, 0.809524, 1, 0, 0.402002,-0.0641319) , 
0, 0.00103014, 1, 0, 0.282478,-0.154592) , 
4, 0.051144, 1, 0, 0.5,2.9839e-06)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926715,0.00657486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861465,0.00535646) , 
25, 1.08637, 1, 0, 0.896989,0.28546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670702,0.00217001) , 
23, -0.222761, 1, 0, 0.826827,0.229963) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626122,0.00293285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262956,-0.00347177) , 
22, -0.230639, 1, 0, 0.441076,-0.0151593) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119462,-0.00584517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394252,-0.00134586) , 
0, 0.00116518, 1, 0, 0.261732,-0.169281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0807175,-0.00688802) , 
25, 1.32284, 1, 0, 0.200556,-0.224274) , 
4, 0.0993826, 1, 0, 0.282478,-0.153048) , 
4, 0.051144, 1, 0, 0.5,3.10938e-06)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00499224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00652249) , 
9, 0.156495, 1, 0, 0.891855,0.277466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00187074) , 
22, -0.212656, 1, 0, 0.826827,0.227666) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189276,-0.00443032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0672414,-0.00680672) , 
25, 1.24629, 1, 0, 0.137001,-0.260075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533225,0.000787248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23391,-0.00393827) , 
17, 0.809524, 1, 0, 0.402002,-0.0623297) , 
0, 0.00103014, 1, 0, 0.282478,-0.151519) , 
4, 0.051144, 1, 0, 0.5,3.13606e-06)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926715,0.00649327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861465,0.00527456) , 
25, 1.08637, 1, 0, 0.896989,0.280081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670702,0.00211696) , 
23, -0.222761, 1, 0, 0.826827,0.225392) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626122,0.00292505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262956,-0.00340412) , 
22, -0.230639, 1, 0, 0.441076,-0.0134945) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.162002,-0.00526131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0730067,-0.00684489) , 
25, 1.19057, 1, 0, 0.12027,-0.287942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303048,-0.00275047) , 
32, 10.9026, 1, 0, 0.200556,-0.22052) , 
4, 0.0993826, 1, 0, 0.282478,-0.150006) , 
4, 0.051144, 1, 0, 0.5,3.24267e-06)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933962,0.00654697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864117,0.00522279) , 
25, 1.08637, 1, 0, 0.902322,0.278875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667186,0.0021407) , 
21, -0.758787, 1, 0, 0.826827,0.223141) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0936768,-0.00625873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211,-0.00387136) , 
0, 0.000783855, 1, 0, 0.137001,-0.255816) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615319,0.00250675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352252,-0.00201156) , 
4, 0.147585, 1, 0, 0.487527,0.0158348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208704,-0.00474146) , 
25, 1.32089, 1, 0, 0.402002,-0.0603427) , 
0, 0.00103014, 1, 0, 0.282478,-0.148507) , 
4, 0.051144, 1, 0, 0.5,3.43335e-06)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843875,0.00487247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927675,0.00640578) , 
9, 0.156495, 1, 0, 0.891855,0.269681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649907,0.00179441) , 
22, -0.212656, 1, 0, 0.826827,0.220913) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626122,0.00291176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262956,-0.00334414) , 
22, -0.230639, 1, 0, 0.441076,-0.0121689) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.126692,-0.00557135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416593,-0.000850148) , 
0, 0.00116518, 1, 0, 0.278265,-0.148194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.106585,-0.00625305) , 
25, 1.19397, 1, 0, 0.200556,-0.216683) , 
4, 0.0993826, 1, 0, 0.282478,-0.147024) , 
4, 0.051144, 1, 0, 0.5,3.57059e-06)    );
   return;
};
 
// Clean up
inline void ReadGBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadGBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
